### ISSUE TITLE
Invalid method-object reference in example/rest_03_stock_querying.py in "get_conid with too many conids" commented out code.

### ISSUE THREAD

**Issue by GonzRon** [Voyz/ibind#31]
https://github.com/Voyz/ibind/blob/49ab5b0da6bc6f7168cad6ef1034f0d30c671f7b/examples/rest_03_stock_querying.py#L58

example:
`conids = c.get_conids('AAPL', default_filtering=False).data`

```python
#### get_conid with too many conids ####
Traceback (most recent call last):
  File "/home/ibind/examples/rest_03_stock_querying.py", line 58, in <module>
    conids = c.get_conids('AAPL', default_filtering=False).data
             ^
NameError: name 'c' is not defined
``` 

should be:

`conids = client.stock_conid_by_symbol('AAPL', default_filtering=False).data`

```python
#### get_conid with too many conids ####
Traceback (most recent call last):
  File "/home/ibind/examples/rest_03_stock_querying.py", line 58, in <module>
    conids = client.stock_conid_by_symbol('AAPL', default_filtering=False).data
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ibeam/ibeam_3.12_venv/lib/python3.12/site-packages/ibind/support/py_utils.py", line 51, in ensure_list_args_wrapper
    return func(*args_list, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ibeam/ibeam_3.12_venv/lib/python3.12/site-packages/ibind/client/ibkr_client_mixins/contract_mixin.py", line 302, in stock_conid_by_symbol
    raise RuntimeError(
RuntimeError: Filtering stock "AAPL" returned 3 instruments and 3 contracts using following query: AAPL.
Please use filters to ensure that only one instrument and one contract per symbol is selected in order to avoid conid ambiguity.
Be aware that contracts are filtered as {"isUS": True} by default. Set default_filtering=False to prevent this default filtering or specify custom filters. See inline documentation for more details.
Instruments returned:
<redacted>
```

**Comment by Voyz** [comment]
Hey @GonzRon well spotted! Thanks! I've pushed out the fix 👍
